dist: trusty
sudo: false
language: node_js
node_js:
  - '6'
  - '7'
deploy:
  provider: npm
  email: felix@stkn.org
  api_key:
    secure: fw0QOov9G72Hy/EqGr/nkXmnUbnEsbOETEnK5P4j3eGBz8gm3ndcdWYcZEJeZTCc37RG68XBgv51pgFOWKRUcZoAqcVlMRcwkfixH2PJ+61pnME0Ppw2uFclQ09NDnWsa79v9o7k0cyujr+1spLnSw+u96c8vVnf5bTvOuXAqpEcYxgz/k5ctm89L74BbkTdxoK25OGFZFvHBe+YKC6lFE7YE+q583cvUOFegUF/FbsujzifngagiFyt1tInrchEz74yzovg/1/OcxYfUU7w3F2ukstOqrSVPtTYC880bRsMnpXidlVd5nEh9Satx1NP2HvErrqq2aVQxKqJ0bW8yrtqSG2WVv9Hik3bXMO8ZcUwnvODROi3nRKwvXxO6PGmyBOoy/MEBjQq5pJX+QzqmUs0iaq9O6mF+SeYktBXeJLwfizsC0x4WSIETZ74rEPXgAUHYdHL+f8GUj86eri+TOxJIlqlA1yI52iXK7rHJL02Fi4jw1oOCzksutmg76goYWfxaDZk6YEb1UmvWFspvxEdb1b9QemNaa6rzoFB0dhMyhELYzShw3kVYhkh2ctSOuWf1Rgxfy891y+YwsuIr5bGdoMfHh3uCbjphoodAQ/7SZdJOryPtLoNbdvxRad+8gD+7GUsaXerZ+WqtVouPbXY9297FEkhYjlQTqNzhL8=
  on:
    tags: true
    repo: cebor/angular-highcharts
cache:
  directories:
    - $HOME/.cache/yarn
