sudo: false
language: node_js
node_js: 10
cache: yarn
script:
- npm run build_lib
before_deploy:
- cd ./dist/angular-highcharts
deploy:
  skip_cleanup: true
  provider: npm
  email: felix@stkn.org
  api_key:
    secure: R6Fa2qmjh/pkI1A3V3NAsQ6lIxgOUEaN2WeLMtOJ6tGY8FrbT7ohh70py7qOjYQ80GL080u1FggjhGw/gsbYoylpqHjZnS88vE3oZqQz47oaUlPw0i69qAR/8TlT0wK8NnsBljx1WITrb8IUKHXQTPX4eoSv041sSwwNxcK202h/TZ0Wyexj0wjN8+AA9itWy0/6agk4NtkrLb2B0N1sdP442E7MU42Doc13ftr1pJWA04RC4i2XErgxQoGRdYmqGuvRFOL0gSl4HvYuqM7hlLurTw7zor/7IrYrYKEZbjkZ0PAwOHAqHNxlI9qXpMKvTpVveyUqWpmgsmBafFM5KN3h/UJ5/9ws6FiS3rfaIVvi1Ogcx0ZqWfN0npmOmDepmA77IUEj6ITB0l+JsSkjkD7p1k56SO27mx9WG3cbUDRfszcJvqdqki0u9dNgCqsRzg6BNO07pTjKbMXeOMT07T+L/yzxIrQJksiF6l5XrK4gEHd5ckDBkJw5Su7TV8pt2ayPsQbM26C3vdqgCxs8rs8rKwz1/RABHE9Y0sg18DRmZQ7ZMxEvhLPcsvB1CbjfIo6TZbezwgFAyQhtI3ExzuzhFtJMmE7vfMXDPISSC2WqtUpn7YWUel7jAG/PdkM2Y1PZ+pWd7kco0C+yZkaNbz1c0GIAt4bwB6edQ+UzX88=
  on:
    tags: true
    repo: cebor/angular-highcharts
